/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings1.java
 *
 * Created on Oct 30, 2012, 9:26:46 PM
 */

package UI;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;

/**
 *
 * @author unicorn
 */
public class Settings extends javax.swing.JDialog implements  ActionListener{


    private static int numFields;
    private static ArrayList<String> list = new ArrayList<String>();
    private JPanel jPanel1,jPanel2;
    private JButton jButton1,jButton2;
    private static ArrayList<JTextField> labels = new ArrayList<JTextField>();
    private boolean isRenamed = false;
    /** Creates new form Settings1 */
    public Settings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        initUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Settings dialog = new Settings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void init()
    {
        Properties prop = new Properties();

    	try {
               //load a properties file
    		prop.load(new FileInputStream("config.properties"));

               //get the property value and print it out
                numFields = Integer.parseInt(prop.getProperty("numberOfFields"));

                list.clear();
                for(int i = 0;i < numFields ; i++)
                {
                    list.add(prop.getProperty("Field"+i));
                }


    	} catch (IOException ex) {
    		ex.printStackTrace();
        }
    }

  private void initUI()
    {
        TitledBorder title;
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jButton1 = new JButton("rename");
        jButton2 = new JButton("cancel");
        jButton1.setSize(80, 40);
        jButton2.setSize(80, 40);
        jButton1.setActionCommand("rename");
        jButton2.setActionCommand("cancel");
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);

        jPanel1.setLayout(new GridLayout(0, 1,1,8));
        title = BorderFactory.createTitledBorder("Current Settings");
        setLayout(new BorderLayout());
        jPanel1.setBorder(title);
        add(jPanel1, BorderLayout.WEST);
        add(jPanel1, BorderLayout.NORTH);

        labels.clear();

        for(int i = 0; i<list.size() ;i++)
        {
            labels.add(new JTextField(list.get(i)));
            labels.get(i).setEditable(false);
            jPanel1.add(labels.get(i));
        }

        jPanel2.setLayout(new GridLayout(1, 3));
        jPanel2.setLayout(new FlowLayout(FlowLayout.CENTER,30,40));
        add(jPanel2);
       jPanel2.add(jButton1);
       jPanel2.add(jButton2);

    }

    public void actionPerformed(ActionEvent e) {
        if("cancel".equals(e.getActionCommand()))
        {
            this.dispose();
        }
        else if("rename".equals(e.getActionCommand()))
        {
            if(isRenamed)
            {
                 Properties prop = new Properties();

                try
                {
                    prop.setProperty("numberOfFields", list.size()+"");
                    for(int i= 0; i <list.size();i++)
                    {
                        prop.setProperty("Field"+i, labels.get(i).getText());
                    }
                    prop.store(new FileOutputStream("config.properties"), null);
                    this.dispose();

                } catch (IOException ex) {
                        ex.printStackTrace();
                        }
            }
            else
            {
                jButton1.setText("Finished");
                isRenamed = true;
                for(int i =0;i<labels.size();i++)
                    labels.get(i).setEditable(true);
            }
        }
         else
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
